# Generated by Django 3.1.4 on 2020-12-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='ФИО')),
                ('gender', models.CharField(choices=[('M', 'Man'), ('F', 'Female')], max_length=1, verbose_name='Пол')),
                ('age', models.IntegerField()),
                ('react_time', models.IntegerField()),
                ('date', models.DateField()),
                ('e_voltage', models.FloatField(verbose_name='Напряжение')),
            ],
        ),
    ]
