# Generated by Django 3.1.4 on 2020-12-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата и Время'),
        ),
        migrations.AlterField(
            model_name='person',
            name='e_voltage',
            field=models.FloatField(blank=True, verbose_name='Напряжение'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(default='anonimous', max_length=40, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='react_time',
            field=models.IntegerField(verbose_name='Время Реакции'),
        ),
    ]
