# Generated by Django 3.1.4 on 2020-12-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonData', '0004_auto_20201214_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='e_voltage',
            field=models.FloatField(blank=True, default=0, verbose_name='Напряжение'),
        ),
    ]
