# Generated by Django 3.1.4 on 2020-12-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonData', '0005_auto_20201214_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date',
        ),
        migrations.AddField(
            model_name='person',
            name='test_variant',
            field=models.CharField(choices=[('E', 'Electro'), ('C', 'Computer')], default='E', max_length=30, verbose_name='Вариант Теста'),
        ),
    ]
