# Generated by Django 3.1.4 on 2020-12-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonData', '0006_auto_20201214_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='test_variant',
            field=models.CharField(choices=[('E', 'Electro'), ('C', 'Computer'), ('V', 'Vibration'), ('S', 'StereoSound'), ('M', 'MonoSound'), ('PP', 'PicturePress'), ('PR', 'PictureRelease')], default='E', max_length=30, verbose_name='Вариант Теста'),
        ),
    ]
